[package]
name = "clippy-reviewdog-filter"
version = "0.1.1"
edition = "2018"
authors = ["Masaki Hara <ackie.h.gmai@gmail.com>"]

[dependencies]
log = "0.4.11"
env_logger = "0.7.1"
clap = "2.33.3"
semver = "0.10.0"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
xml-rs = "0.8.3"
