[package]
name = "clippy-reviewdog-filter"
version = "0.1.0"
authors = ["Masaki Hara <ackie.h.gmai@gmail.com>"]

[dependencies]
semver = "0.9.0"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.32"
xml-rs = "0.8.0"
